name: cse587_midterm
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=25.0
  - pip:
      - ipython==8.32.0
      - numpy==1.26.4
      - pandas==2.2.3
      - nltk==3.9.1
      - scikit_learn==1.6.1
      - gensim==4.3.3
